name: Auto-Publish Articles

on:
  schedule:
    - cron: '30 12 * * *'  # 7:30 AM EST = 12:30 PM UTC
  workflow_dispatch:

jobs:
  publish-article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Publish Article
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
      run: |
        python publish_article.py
